sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dU5xp3mLA6gRsxYQTxuE1Bo6Yl7GdmoZxbTHiO04+NjVMAM0gsallfGqL7RieAV0k1FyAZ02rCV6a2JOCcPS5J/QlrZ3xaT0aS85Nv5j1MVzdExLpEOmRZsQDNdaMLZH2TIHLID68Iyp3YX6D4etpaF/u2qNEAbFGvL7BSekJac7MXVNTERvyhXRU8aV+uxEUu+Ah68eT0QrDpPP82eer/QbMFvltgUL08y9hW4O8K0LlLV1b3FJupTSwks/SB7lJ34tgUHA8MepBFnGB7+QEXwVTU4gXnc228IZbJyWgYzNevhcYJ44yXX6KUhlymRBCHrgy9MgWl3oI0z/PoypA7d9FyTg1ANI521Zt7Hz+k5XSYYLZP6rdO0HYwY8gyZ5p0XfP41nLOmQmwkdpbz9ePf7EZTKs00qXaJ7biBnA2eXw/fipyrArd10muoqq4Tvicm2/qTBrg5aWRpN4YOY4v31qItYVUE3PgQDX8Bijg+zAxz3YMrjnxcF6bKJgtXrzWSixhtBQ9YqHFiUm/SCFAkqhuCsI7+mTdxsSRmh4fEnsrlsPKGlCy+YbY+lehorwdxM9mYVBImKwVgVfNqmLzgvAbHR1wHEHWrm2JbRvx+FukQS3izwtsOjvrAxoHVRd0WBcI8nLM5y6FdcAxCYHQNMdXtibnBRTMQeLQRR+UM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Divina-Commedia-di-Dante-Purgatorio_998
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy